import type { CatalogEntry, CommandCatalogEntry, StructureCatalogEntry } from "./types";
import { isCommandEntry, isStructureEntry } from "./types";

const STRUCTURE_DATA: StructureCatalogEntry[] = [
  {
    id: "watchtower",
    name: "Watchtower",
    kind: "structure",
    fluxCost: 60,
    buildSeconds: 12,
    requiredRelayTier: 1,
    requiredSignalCounts: { Vanguard: 1 },
    signalTypes: ["Vanguard"],
    productionSeconds: 18,
    producedSizeClass: "Swarm",
    producedPop: 4,
    localPopCap: 8,
    maxHp: 220,
    damagePerTick: 0,
    producedAntiClass: "Heavy",
    maxCharges: 3,
    chargeCooldownSeconds: 25,
    producedFlavor: "Swarm scouts (ranged, fast, fragile)",
  },
  {
    id: "root_bunker",
    name: "Root Bunker",
    kind: "structure",
    fluxCost: 70,
    buildSeconds: 14,
    requiredRelayTier: 1,
    requiredSignalCounts: { Bastion: 1 },
    signalTypes: ["Bastion"],
    productionSeconds: 16,
    producedSizeClass: "Line",
    producedPop: 2,
    localPopCap: 6,
    maxHp: 320,
    damagePerTick: 0,
    producedAntiClass: "Swarm",
    maxCharges: 3,
    chargeCooldownSeconds: 28,
    aura: { kind: "turret", radius: 6, value: 0.8 },
    producedFlavor: "Line sentinels (melee, shielded)",
  },
  {
    id: "menders_hut",
    name: "Mender's Hut",
    kind: "structure",
    fluxCost: 60,
    buildSeconds: 11,
    requiredRelayTier: 1,
    requiredSignalCounts: { Reclaim: 1 },
    signalTypes: ["Reclaim"],
    productionSeconds: 20,
    producedSizeClass: "Line",
    producedPop: 2,
    localPopCap: 4,
    maxHp: 180,
    damagePerTick: 0,
    maxCharges: 3,
    chargeCooldownSeconds: 22,
    aura: { kind: "heal_structures", radius: 8, value: 1.5 },
    producedFlavor: "Line medics (heal nearest ally)",
  },
  {
    id: "siege_works",
    name: "Siege Works",
    kind: "structure",
    fluxCost: 150,
    buildSeconds: 18,
    requiredRelayTier: 2,
    requiredSignalCounts: { Vanguard: 2 },
    signalTypes: ["Vanguard", "Vanguard"],
    productionSeconds: 30,
    producedSizeClass: "Heavy",
    producedPop: 4,
    localPopCap: 8,
    maxHp: 380,
    damagePerTick: 0,
    producedAntiClass: "Line",
    maxCharges: 2,
    chargeCooldownSeconds: 45,
    unitTrait: "anti_building",
    producedFlavor: "Heavy rams (ignore 50% building armor)",
  },
  {
    id: "bastion_keep",
    name: "Bastion Keep",
    kind: "structure",
    fluxCost: 180,
    buildSeconds: 20,
    requiredRelayTier: 2,
    requiredSignalCounts: { Bastion: 2 },
    signalTypes: ["Bastion", "Bastion"],
    productionSeconds: 28,
    producedSizeClass: "Heavy",
    producedPop: 4,
    localPopCap: 8,
    maxHp: 520,
    damagePerTick: 0,
    producedAntiClass: "Line",
    maxCharges: 2,
    chargeCooldownSeconds: 50,
    aura: { kind: "turret", radius: 7, value: 0.6 },
    producedFlavor: "Heavy knights (high HP melee)",
  },
  {
    id: "salvage_yard",
    name: "Salvage Yard",
    kind: "structure",
    fluxCost: 120,
    buildSeconds: 15,
    requiredRelayTier: 2,
    requiredSignalCounts: { Reclaim: 2 },
    signalTypes: ["Reclaim", "Reclaim"],
    productionSeconds: 16,
    producedSizeClass: "Swarm",
    producedPop: 4,
    localPopCap: 8,
    maxHp: 260,
    damagePerTick: 0,
    producedAntiClass: "Swarm",
    maxCharges: 2,
    chargeCooldownSeconds: 35,
    aura: { kind: "salvage_bonus", radius: 12, value: 0.2 },
    producedFlavor: "Swarm scrappers (fast melee)",
  },
  {
    id: "war_camp",
    name: "War Camp",
    kind: "structure",
    fluxCost: 140,
    buildSeconds: 16,
    requiredRelayTier: 2,
    requiredSignalCounts: { Vanguard: 1, Bastion: 1 },
    signalTypes: ["Vanguard", "Bastion"],
    productionSeconds: 14,
    producedSizeClass: "Line",
    producedPop: 2,
    localPopCap: 8,
    maxHp: 300,
    damagePerTick: 0,
    producedAntiClass: "Heavy",
    maxCharges: 2,
    chargeCooldownSeconds: 40,
    aura: { kind: "safe_deploy_radius", radius: 10, value: 1 },
    producedFlavor: "Line soldiers (balanced melee)",
  },
  {
    id: "raid_nest",
    name: "Raid Nest",
    kind: "structure",
    fluxCost: 130,
    buildSeconds: 15,
    requiredRelayTier: 2,
    requiredSignalCounts: { Vanguard: 1, Reclaim: 1 },
    signalTypes: ["Vanguard", "Reclaim"],
    productionSeconds: 15,
    producedSizeClass: "Swarm",
    producedPop: 4,
    localPopCap: 8,
    maxHp: 240,
    damagePerTick: 0,
    producedAntiClass: "Swarm",
    maxCharges: 2,
    chargeCooldownSeconds: 38,
    unitTrait: "lifesteal",
    producedFlavor: "Swarm raiders (heal on kill)",
  },
  {
    id: "root_garden",
    name: "Root Garden",
    kind: "structure",
    fluxCost: 130,
    buildSeconds: 16,
    requiredRelayTier: 2,
    requiredSignalCounts: { Reclaim: 1, Bastion: 1 },
    signalTypes: ["Reclaim", "Bastion"],
    productionSeconds: 18,
    producedSizeClass: "Line",
    producedPop: 2,
    localPopCap: 6,
    maxHp: 280,
    damagePerTick: 0,
    producedAntiClass: "Line",
    maxCharges: 2,
    chargeCooldownSeconds: 40,
    aura: { kind: "heal_structures", radius: 10, value: 2 },
    producedFlavor: "Line thorns (ranged, poison DoT)",
  },
  {
    id: "dragon_roost",
    name: "Dragon Roost",
    kind: "structure",
    fluxCost: 280,
    buildSeconds: 22,
    requiredRelayTier: 3,
    requiredSignalCounts: { Vanguard: 2 },
    signalTypes: ["Vanguard", "Vanguard"],
    productionSeconds: 50,
    producedSizeClass: "Titan",
    producedPop: 8,
    localPopCap: 8,
    maxHp: 640,
    damagePerTick: 0,
    producedAntiClass: "Swarm",
    maxCharges: 1,
    chargeCooldownSeconds: 90,
    unitAoeRadius: 3.5,
    unitFlying: true,
    producedFlavor: "Titan wyvern (flying, AoE breath)",
  },
  {
    id: "ironhold_citadel",
    name: "Ironhold Citadel",
    kind: "structure",
    fluxCost: 300,
    buildSeconds: 24,
    requiredRelayTier: 3,
    requiredSignalCounts: { Bastion: 2 },
    signalTypes: ["Bastion", "Bastion"],
    productionSeconds: 55,
    producedSizeClass: "Titan",
    producedPop: 8,
    localPopCap: 8,
    maxHp: 780,
    damagePerTick: 0,
    producedAntiClass: "Heavy",
    maxCharges: 1,
    chargeCooldownSeconds: 95,
    aura: { kind: "turret", radius: 8, value: 1.2 },
    producedFlavor: "Titan golem (massive HP, slow)",
  },
  {
    id: "reclamation_spire",
    name: "Reclamation Spire",
    kind: "structure",
    fluxCost: 250,
    buildSeconds: 22,
    requiredRelayTier: 3,
    requiredSignalCounts: { Reclaim: 2 },
    signalTypes: ["Reclaim", "Reclaim"],
    productionSeconds: 35,
    producedSizeClass: "Heavy",
    producedPop: 4,
    localPopCap: 8,
    maxHp: 440,
    damagePerTick: 0,
    producedAntiClass: "Titan",
    maxCharges: 1,
    chargeCooldownSeconds: 80,
    salvageRefundFrac: 1,
    producedFlavor: "Heavy wraith (ranged, anti-Titan)",
  },
];

const COMMAND_DATA: CommandCatalogEntry[] = [
  {
    id: "recycle",
    name: "Recycle",
    kind: "command",
    fluxCost: 40,
    requiredRelayTier: 1,
    requiredSignalCounts: { Reclaim: 1 },
    signalTypes: ["Reclaim"],
    salvagePctOnCast: 100,
    maxCharges: 2,
    chargeCooldownSeconds: 35,
    effect: { type: "recycle_structure" },
  },
  {
    id: "fortify",
    name: "Fortify",
    kind: "command",
    fluxCost: 60,
    requiredRelayTier: 1,
    requiredSignalCounts: { Bastion: 1 },
    signalTypes: ["Bastion"],
    salvagePctOnCast: 100,
    maxCharges: 2,
    chargeCooldownSeconds: 40,
    effect: { type: "buff_structure", damageReductionPct: 50, durationSeconds: 15 },
  },
  {
    id: "firestorm",
    name: "Firestorm",
    kind: "command",
    fluxCost: 80,
    requiredRelayTier: 1,
    requiredSignalCounts: { Vanguard: 1 },
    signalTypes: ["Vanguard"],
    salvagePctOnCast: 100,
    maxCharges: 2,
    chargeCooldownSeconds: 45,
    effect: { type: "aoe_damage", radius: 7, damage: 120 },
  },
  {
    id: "muster",
    name: "Muster",
    kind: "command",
    fluxCost: 50,
    requiredRelayTier: 1,
    salvagePctOnCast: 100,
    maxCharges: 3,
    chargeCooldownSeconds: 30,
    signalTypes: ["Vanguard"],
    effect: { type: "muster_structure" },
  },
  {
    id: "shatter",
    name: "Shatter",
    kind: "command",
    fluxCost: 100,
    requiredRelayTier: 2,
    requiredSignalCounts: { Vanguard: 1, Bastion: 1 },
    signalTypes: ["Vanguard", "Bastion"],
    salvagePctOnCast: 100,
    maxCharges: 1,
    chargeCooldownSeconds: 55,
    effect: { type: "shatter_structure", damage: 300, silenceSeconds: 10 },
  },
];

export const CATALOG: CatalogEntry[] = [...STRUCTURE_DATA, ...COMMAND_DATA];

export const CATALOG_BY_ID: Record<string, CatalogEntry> = Object.fromEntries(
  CATALOG.map((c) => [c.id, c]),
);

export const STRUCTURES: StructureCatalogEntry[] = CATALOG.filter(isStructureEntry);

export const COMMANDS: CommandCatalogEntry[] = CATALOG.filter(isCommandEntry);

export const COMMAND_BY_ID: Record<string, CommandCatalogEntry> = Object.fromEntries(
  COMMANDS.map((c) => [c.id, c]),
);

/** Default 16-slot loadout for first boot / reset. */
export const DEFAULT_DOCTRINE_SLOTS: (string | null)[] = [
  "watchtower",
  "root_bunker",
  "menders_hut",
  "recycle",
  "siege_works",
  "war_camp",
  "salvage_yard",
  "raid_nest",
  "bastion_keep",
  "root_garden",
  "dragon_roost",
  "ironhold_citadel",
  "reclamation_spire",
  "fortify",
  "firestorm",
  "shatter",
];

export function getCatalogEntry(id: string | null | undefined): CatalogEntry | null {
  if (!id) return null;
  return CATALOG_BY_ID[id] ?? null;
}
