import type { CatalogEntry, CommandCatalogEntry, StructureCatalogEntry } from "./types";
import { isCommandEntry, isStructureEntry } from "./types";

const STRUCTURE_DATA: StructureCatalogEntry[] = [
  {
    id: "watchtower",
    name: "Watchtower",
    kind: "structure",
    fluxCost: 60,
    buildSeconds: 12,
    requiredRelayTier: 1,
    requiredSignalCounts: { Vanguard: 1 },
    signalTypes: ["Vanguard"],
    productionSeconds: 18,
    producedSizeClass: "Swarm",
    producedPop: 4,
    localPopCap: 8,
    maxHp: 220,
    damagePerTick: 0,
    producedAntiClass: "Heavy",
    maxCharges: 3,
    chargeCooldownSeconds: 25,
  },
  {
    id: "root_bunker",
    name: "Root Bunker",
    kind: "structure",
    fluxCost: 70,
    buildSeconds: 14,
    requiredRelayTier: 1,
    requiredSignalCounts: { Bastion: 1 },
    signalTypes: ["Bastion"],
    productionSeconds: 16,
    producedSizeClass: "Line",
    producedPop: 2,
    localPopCap: 6,
    maxHp: 320,
    damagePerTick: 0.08,
    producedAntiClass: "Swarm",
    maxCharges: 3,
    chargeCooldownSeconds: 28,
  },
  {
    id: "menders_hut",
    name: "Mender's Hut",
    kind: "structure",
    fluxCost: 60,
    buildSeconds: 11,
    requiredRelayTier: 1,
    requiredSignalCounts: { Reclaim: 1 },
    signalTypes: ["Reclaim"],
    productionSeconds: 20,
    producedSizeClass: "Line",
    producedPop: 2,
    localPopCap: 4,
    maxHp: 180,
    damagePerTick: 0,
    maxCharges: 3,
    chargeCooldownSeconds: 22,
  },
  {
    id: "siege_works",
    name: "Siege Works",
    kind: "structure",
    fluxCost: 150,
    buildSeconds: 18,
    requiredRelayTier: 2,
    requiredSignalCounts: { Vanguard: 2 },
    signalTypes: ["Vanguard", "Vanguard"],
    productionSeconds: 30,
    producedSizeClass: "Heavy",
    producedPop: 4,
    localPopCap: 8,
    maxHp: 380,
    damagePerTick: 0,
    producedAntiClass: "Line",
    maxCharges: 2,
    chargeCooldownSeconds: 45,
  },
  {
    id: "bastion_keep",
    name: "Bastion Keep",
    kind: "structure",
    fluxCost: 180,
    buildSeconds: 20,
    requiredRelayTier: 2,
    requiredSignalCounts: { Bastion: 2 },
    signalTypes: ["Bastion", "Bastion"],
    productionSeconds: 28,
    producedSizeClass: "Heavy",
    producedPop: 4,
    localPopCap: 8,
    maxHp: 520,
    damagePerTick: 0.06,
    producedAntiClass: "Line",
    maxCharges: 2,
    chargeCooldownSeconds: 50,
  },
  {
    id: "salvage_yard",
    name: "Salvage Yard",
    kind: "structure",
    fluxCost: 120,
    buildSeconds: 15,
    requiredRelayTier: 2,
    requiredSignalCounts: { Reclaim: 2 },
    signalTypes: ["Reclaim", "Reclaim"],
    productionSeconds: 16,
    producedSizeClass: "Swarm",
    producedPop: 4,
    localPopCap: 8,
    maxHp: 260,
    damagePerTick: 0,
    producedAntiClass: "Swarm",
    maxCharges: 2,
    chargeCooldownSeconds: 35,
  },
  {
    id: "war_camp",
    name: "War Camp",
    kind: "structure",
    fluxCost: 140,
    buildSeconds: 16,
    requiredRelayTier: 2,
    requiredSignalCounts: { Vanguard: 1, Bastion: 1 },
    signalTypes: ["Vanguard", "Bastion"],
    productionSeconds: 14,
    producedSizeClass: "Line",
    producedPop: 2,
    localPopCap: 8,
    maxHp: 300,
    damagePerTick: 0,
    producedAntiClass: "Heavy",
    maxCharges: 2,
    chargeCooldownSeconds: 40,
  },
  {
    id: "raid_nest",
    name: "Raid Nest",
    kind: "structure",
    fluxCost: 130,
    buildSeconds: 15,
    requiredRelayTier: 2,
    requiredSignalCounts: { Vanguard: 1, Reclaim: 1 },
    signalTypes: ["Vanguard", "Reclaim"],
    productionSeconds: 15,
    producedSizeClass: "Swarm",
    producedPop: 4,
    localPopCap: 8,
    maxHp: 240,
    damagePerTick: 0,
    producedAntiClass: "Swarm",
    maxCharges: 2,
    chargeCooldownSeconds: 38,
  },
  {
    id: "dragon_roost",
    name: "Dragon Roost",
    kind: "structure",
    fluxCost: 280,
    buildSeconds: 22,
    requiredRelayTier: 3,
    requiredSignalCounts: { Vanguard: 2, Reclaim: 1 },
    signalTypes: ["Vanguard", "Vanguard", "Reclaim"],
    productionSeconds: 50,
    producedSizeClass: "Titan",
    producedPop: 8,
    localPopCap: 8,
    maxHp: 640,
    damagePerTick: 0.1,
    producedAntiClass: "Swarm",
    maxCharges: 1,
    chargeCooldownSeconds: 90,
  },
  {
    id: "ironhold_citadel",
    name: "Ironhold Citadel",
    kind: "structure",
    fluxCost: 300,
    buildSeconds: 24,
    requiredRelayTier: 3,
    requiredSignalCounts: { Bastion: 2, Reclaim: 1 },
    signalTypes: ["Bastion", "Bastion", "Reclaim"],
    productionSeconds: 55,
    producedSizeClass: "Titan",
    producedPop: 8,
    localPopCap: 8,
    maxHp: 780,
    damagePerTick: 0.08,
    producedAntiClass: "Heavy",
    maxCharges: 1,
    chargeCooldownSeconds: 95,
  },
];

const COMMAND_DATA: CommandCatalogEntry[] = [
  {
    id: "recycle",
    name: "Recycle",
    kind: "command",
    fluxCost: 40,
    requiredRelayTier: 1,
    requiredSignalCounts: { Reclaim: 1 },
    signalTypes: ["Reclaim"],
    salvagePctOnCast: 100,
    maxCharges: 2,
    chargeCooldownSeconds: 35,
    effect: { type: "recycle_structure" },
  },
  {
    id: "fortify",
    name: "Fortify",
    kind: "command",
    fluxCost: 60,
    requiredRelayTier: 1,
    requiredSignalCounts: { Bastion: 1 },
    signalTypes: ["Bastion"],
    salvagePctOnCast: 100,
    maxCharges: 2,
    chargeCooldownSeconds: 40,
    effect: { type: "noop" },
  },
  {
    id: "firestorm",
    name: "Firestorm",
    kind: "command",
    fluxCost: 80,
    requiredRelayTier: 1,
    requiredSignalCounts: { Vanguard: 1 },
    signalTypes: ["Vanguard"],
    salvagePctOnCast: 100,
    maxCharges: 2,
    chargeCooldownSeconds: 45,
    effect: { type: "noop" },
  },
  {
    id: "muster",
    name: "Muster",
    kind: "command",
    fluxCost: 50,
    requiredRelayTier: 1,
    salvagePctOnCast: 100,
    maxCharges: 3,
    chargeCooldownSeconds: 30,
    signalTypes: ["Vanguard"],
    effect: { type: "noop" },
  },
];

export const CATALOG: CatalogEntry[] = [...STRUCTURE_DATA, ...COMMAND_DATA];

export const CATALOG_BY_ID: Record<string, CatalogEntry> = Object.fromEntries(
  CATALOG.map((c) => [c.id, c]),
);

export const STRUCTURES: StructureCatalogEntry[] = CATALOG.filter(isStructureEntry);

export const COMMANDS: CommandCatalogEntry[] = CATALOG.filter(isCommandEntry);

export const COMMAND_BY_ID: Record<string, CommandCatalogEntry> = Object.fromEntries(
  COMMANDS.map((c) => [c.id, c]),
);

/** Default 16-slot loadout for first boot / reset. */
export const DEFAULT_DOCTRINE_SLOTS: (string | null)[] = [
  "watchtower",
  "root_bunker",
  "menders_hut",
  "recycle",
  "siege_works",
  "war_camp",
  "salvage_yard",
  "raid_nest",
  "bastion_keep",
  "dragon_roost",
  "ironhold_citadel",
  "fortify",
  "firestorm",
  "muster",
  null,
  null,
];

export function getCatalogEntry(id: string | null | undefined): CatalogEntry | null {
  if (!id) return null;
  return CATALOG_BY_ID[id] ?? null;
}
